### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Animals3** [Martin-JC-Xu/P2M#1]
“ if (tmp_edges[end1].find(e_id) == tmp_edges[end1].end())  ” This code have abnormal。  In VS2022 and X64 environment。
<img width="960" alt="0d81ca8f8b3ab1e45bf03460dc36712" src="https://github.com/user-attachments/assets/c42ad576-f9a9-422d-bdb3-2ab6b4807897">

**Comment by Martin-JC-Xu** [comment]
There seems to be something wrong with Voronoi construction. Have you set the `limit_cube_len` value greater than the input coordinate values?

**Comment by Animals3** [comment]
"Yes, limit_cube_len is set to 1e1 (10), and the input coordinate values range between -5 and 5. In the code 'if (tmp_edges[end1].find(e_id) == tmp_edges[end1].end())', we have tmp_edges.size() = 0, end1 = 1584662828, and e_id = 0. This is problematic because end1 is much larger than tmp_edges.size(), which leads to an out-of-bounds access. However, the root cause of this issue is still unclear."

**Comment by Animals3** [comment]
Thank you for replying to my question.
Yes, limit_cube_len is set to 1e1 (10), and the input coordinate values range between -5 and 5. In the code 'if (tmp_edges[end1].find(e_id) == tmp_edges[end1].end())', we have tmp_edges.size() = 0, end1 = 1584662828, and e_id = 0. This is problematic because end1 is much larger than tmp_edges.size(), which leads to an out-of-bounds access. However, the root cause of this issue is still unclear.
![8d48a1f33f474272e5a57e5ba9935de](https://github.com/user-attachments/assets/bcacd7c0-0412-4c72-91df-b6c309107645)

**Comment by Martin-JC-Xu** [comment]
It seems that there are no input points in the construction. Please check your input to the `Model` constructor. Have you saved all the mesh points?

**Comment by Animals3** [comment]
Yes, I have saved all the mesh points.
In the function call 'Model m(points, segments, faces, limit_cube_len);', the incoming parameters have the following properties:
<img width="710" alt="1" src="https://github.com/user-attachments/assets/794c5464-a6aa-4e87-bcf6-f4cef63bcff6">
In the picture, we have Points.size() = 9995, Faces.size() = 20000, and Segments.size() = 0. This is because the .off file model only contains points and faces, but no segments.
Can I contact you via wechat or qq?  my wechat are：13233715722
